### Sign-Up

POST http://localhost:3000/authentication/users/sign-up
Content-Type: application/json

{
    "username": "ian",
    "email": "ian@gmail.com",
    "password": "1fhjjjdjdjfkgksdftkgjrktiekwkfjgktorithfruthfjdkslfjcnfjgkdorie4",
    "firstname": "ian",
    "lastname": "chris",
    "phone": "09105325847",
    "role": "customer"
}


### Sign-In

POST http://localhost:3000/authentication/users/sign-in
Content-Type: application/json

{
    "username": "ian",
    "password": "1fhjjjdjdjfkgksdftkgjrktiekwkfjgktorithfruthfjdkslfjcnfjgkdorie4"
}


### Update User

PATCH http://localhost:3000/authentication/users
Content-Type: application/json

{
    "userId": "1",
    "username": "i4n"
}


### Delete User

DELETE http://localhost:3000/authentication/users
Content-Type: application/json

{
    "userId": "1"
}